services:
  - type: cron
    name: ethiopian-jobs-bot
    runtime: python
    schedule: "0 */8 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: dummy
      - key: CHANNEL_ID
        value: "@trytry1221"
      - key: GIST_TOKEN
        value: dummy
      - key: GIST_ID
        value: dummy
