services:
  - type: cron
    name: ethiopian-jobs-bot
    runtime: python
    schedule: "0 */4 * * *"  # Runs every 4 hours (8AM, 12PM, 4PM, 8PM, 12AM, 4AM)
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: "8191854029:AAFdBYDf5wqAMXEXEubrzLfmsJubF6icm1w"
        sync: false
      - key: "@trytry1221"
        value: "@trytry1221"
    disk:
      name: jobs-data
      mountPath: /var/data
      sizeGB: 1
