services:
  - type: cron
    name: ethiopian-jobs-bot
    runtime: python
    schedule: "*/5 * * * *"  # Runs every 5 minutes for testing!
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "@trytry1221"
      - key: GIST_TOKEN
        sync: false
      - key: GIST_ID
        sync: false
